figure()
# t=range(1,length=N,stop=2-0.01)
# t2=range(t1[end],step=h2_opt/2000,length=21)
# t3=range(t2[end],step=h3_opt/2000,length=21)
# t4=range(t3[end],step=h4_opt/2000,length=5)
# t=vcat(t1,t2,t3,t4)

subplot(411)
plot(t,x_opt[:,1],label="q1")
plot(t,x_opt[:,2],label="q2")
plot(t,x_opt[:,3],label="q3")
plot(t,x_opt[:,4],label="q4")
plot(t,x_opt[:,5],label="q5")
plot(t,x_opt[:,6],label="q6")
plot(t,x_opt[:,7],label="q7")
plot(t,x_opt[:,8],label="q8")
plot(t,x_opt[:,9],label="q9")
grid(true)
legend()
subplot(412)
plot(t,x_opt[:,10],label="q1d")
plot(t,x_opt[:,11],label="q2d")
plot(t,x_opt[:,12],label="q3d")
plot(t,x_opt[:,13],label="q4d")
plot(t,x_opt[:,14],label="q5d")
plot(t,x_opt[:,15],label="q6d")
plot(t,x_opt[:,16],label="q7d")
plot(t,x_opt[:,17],label="q8d")
plot(t,x_opt[:,18],label="q9d")
grid(true)
legend()
subplot(413)
plot(t,x_opt[:,28],label="tau2")
plot(t,x_opt[:,29],label="tau3")
plot(t,x_opt[:,30],label="tau4")
plot(t,x_opt[:,31],label="tau5")
plot(t,x_opt[:,32],label="tau6")
plot(t,x_opt[:,33],label="tau7")
# legend(["u1","u2","u3","u4","u5"])
legend()
grid(true)
subplot(414)
plot(t,x_opt[:,34],label="lambda1")
plot(t,x_opt[:,35],label="lambda2")
plot(t,x_opt[:,36],label="lambda3")
plot(t,x_opt[:,37],label="lambda4")
plot(t,x_opt[:,38],label="lambda5")
plot(t,x_opt[:,39],label="lambda6")
legend()
grid(true)
# plot(t,lambda2.(x_opt[:,1],x_opt[:,2],x_opt[:,3],x_opt[:,4],x_opt[:,5],x_opt[:,6],x_opt[:,7],x_opt[:,8],x_opt[:,9],x_opt[:,10],x_opt[:,11],x_opt[:,12],x_opt[:,13],x_opt[:,14],x_opt[:,15]),label="VGRF")
