using BSON: @save, @load

@load datafilename t x_opt t_opt h1_opt h2_opt h3_opt h4_opt # opt_output

# x1_des=CubicSplineInterpolation(t,x_opt[:,1],extrapolation_bc = Line())	# Flat() vs Line()
# x2_des=CubicSplineInterpolation(t,x_opt[:,2],extrapolation_bc = Line())	# use line for smooth transition
# x3_des=CubicSplineInterpolation(t,x_opt[:,3],extrapolation_bc = Line())
# x4_des=CubicSplineInterpolation(t,x_opt[:,4],extrapolation_bc = Line())
# x5_des=CubicSplineInterpolation(t,x_opt[:,5],extrapolation_bc = Line())
# x6_des=CubicSplineInterpolation(t,x_opt[:,6],extrapolation_bc = Line())
# x7_des=CubicSplineInterpolation(t,x_opt[:,7],extrapolation_bc = Line())
# x8_des=CubicSplineInterpolation(t,x_opt[:,8],extrapolation_bc = Line())
# x9_des=CubicSplineInterpolation(t,x_opt[:,9],extrapolation_bc = Line())
# x10_des=CubicSplineInterpolation(t,x_opt[:,10],extrapolation_bc = Line())
# x11_des=CubicSplineInterpolation(t,x_opt[:,11],extrapolation_bc = Line())
# x12_des=CubicSplineInterpolation(t,x_opt[:,12],extrapolation_bc = Line())
# x13_des=CubicSplineInterpolation(t,x_opt[:,13],extrapolation_bc = Line())
# x14_des=CubicSplineInterpolation(t,x_opt[:,14],extrapolation_bc = Line())
# x15_des=CubicSplineInterpolation(t,x_opt[:,15],extrapolation_bc = Line())
# x16_des=CubicSplineInterpolation(t,x_opt[:,16],extrapolation_bc = Line())
# x17_des=CubicSplineInterpolation(t,x_opt[:,17],extrapolation_bc = Line())
# x18_des=CubicSplineInterpolation(t,x_opt[:,18],extrapolation_bc = Line())
# x19_des=CubicSplineInterpolation(t,x_opt[:,19],extrapolation_bc = Line())
# x20_des=CubicSplineInterpolation(t,x_opt[:,20],extrapolation_bc = Line())
# x21_des=CubicSplineInterpolation(t,x_opt[:,21],extrapolation_bc = Line())
# x22_des=CubicSplineInterpolation(t,x_opt[:,22],extrapolation_bc = Line())
# x23_des=CubicSplineInterpolation(t,x_opt[:,23],extrapolation_bc = Line())
# x24_des=CubicSplineInterpolation(t,x_opt[:,24],extrapolation_bc = Line())
# x25_des=CubicSplineInterpolation(t,x_opt[:,25],extrapolation_bc = Line())
# x26_des=CubicSplineInterpolation(t,x_opt[:,26],extrapolation_bc = Line())
# x27_des=CubicSplineInterpolation(t,x_opt[:,27],extrapolation_bc = Line())
# x28_des=CubicSplineInterpolation(t,x_opt[:,28],extrapolation_bc = Line())
# x29_des=CubicSplineInterpolation(t,x_opt[:,29],extrapolation_bc = Line())
# x30_des=CubicSplineInterpolation(t,x_opt[:,30],extrapolation_bc = Line())
# x31_des=CubicSplineInterpolation(t,x_opt[:,31],extrapolation_bc = Line())
# x32_des=CubicSplineInterpolation(t,x_opt[:,32],extrapolation_bc = Line())
# x33_des=CubicSplineInterpolation(t,x_opt[:,33],extrapolation_bc = Line())
# x34_des=CubicSplineInterpolation(t,x_opt[:,34],extrapolation_bc = Line())
# x35_des=CubicSplineInterpolation(t,x_opt[:,35],extrapolation_bc = Line())
# x36_des=CubicSplineInterpolation(t,x_opt[:,36],extrapolation_bc = Line())
# x37_des=CubicSplineInterpolation(t,x_opt[:,37],extrapolation_bc = Line())
# x38_des=CubicSplineInterpolation(t,x_opt[:,38],extrapolation_bc = Line())
# x39_des=CubicSplineInterpolation(t,x_opt[:,39],extrapolation_bc = Line())

# desiredTrajectory=(x1_des,x2_des,x3_des,x4_des,x5_des,x6_des,x7_des,x8_des,x9_des,x10_des,x11_des,x12_des,x13_des,x14_des,x15_des)